"""Data coverage report for the target cities -> docs/DATA_QUALITY.md (SPEC §3.2: report gaps honestly).

Run: uv run python -m cleanair.data.quality_report
"""

import argparse
from pathlib import Path

import duckdb

TARGET_CITIES = ("Delhi", "Kanpur", "Lucknow", "Mumbai")

QUERY = """
WITH span AS (SELECT min(date) AS d0, max(date) AS d1 FROM city_aqi_daily),
days AS (SELECT unnest(generate_series(d0, d1, INTERVAL 1 DAY))::DATE AS date FROM span),
grid AS (SELECT c.city, d.date FROM (SELECT unnest(?::VARCHAR[]) AS city) c CROSS JOIN days d),
joined AS (SELECT g.city, g.date, a.aqi, a.aqi_category, a.stations_reporting, a.stations_total
           FROM grid g LEFT JOIN city_aqi_daily a USING (city, date)),
runs AS (SELECT city, date, aqi_category IS NULL AS missing,
                row_number() OVER (PARTITION BY city ORDER BY date)
                - row_number() OVER (PARTITION BY city, aqi_category IS NULL ORDER BY date) AS grp
         FROM joined)
SELECT j.city,
       count(*) AS days_in_range,
       count(j.aqi_category) AS days_reported,
       round(100.0 * count(j.aqi_category) / count(*), 1) AS pct_days_reported,
       count(*) FILTER (j.aqi_category IS NOT NULL AND j.aqi IS NULL) AS days_category_only,
       round(100.0 * avg(j.stations_reporting::DOUBLE / nullif(j.stations_total, 0)), 1) AS mean_station_coverage_pct,
       (SELECT max(n) FROM (SELECT count(*) AS n FROM runs r WHERE r.city = j.city AND r.missing GROUP BY grp))
         AS longest_gap_days
FROM joined j GROUP BY j.city ORDER BY j.city
"""


def report(db_path: Path, cities: tuple[str, ...] = TARGET_CITIES) -> str:
    con = duckdb.connect(str(db_path), read_only=True)
    try:
        span = con.execute("SELECT min(date), max(date), count(DISTINCT city), count(*) FROM city_aqi_daily").fetchone()
        rows = con.execute(QUERY, [list(cities)]).fetchall()
        cols = [d[0] for d in con.description]
    finally:
        con.close()
    lines = [
        "# Data quality: CPCB daily AQI bulletins",
        "",
        f"Range {span[0]} → {span[1]}; {span[2]} cities; {span[3]} city-days in `city_aqi_daily`.",
        "Generated by `python -m cleanair.data.quality_report`. Answers must state coverage (SPEC §8.1).",
        "",
        "| " + " | ".join(cols) + " |",
        "|" + "---|" * len(cols),
    ]
    lines += ["| " + " | ".join("—" if v is None else str(v) for v in r) + " |" for r in rows]
    lines += [
        "",
        "- `days_category_only`: the bulletin gave the AQI category but its value cell had no text "
        "(stored as NULL AQI).",
        "- `mean_station_coverage_pct`: mean of stations_reporting / stations_total on reported days.",
        "- Missing days are bulletins CPCB did not publish or that failed to download; they are not imputed.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Write the data coverage report.")
    p.add_argument("--db", type=Path, default=Path("data/aq.duckdb"))
    p.add_argument("--out", type=Path, default=Path("docs/DATA_QUALITY.md"))
    args = p.parse_args(argv)
    text = report(args.db)
    args.out.write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
